const REPO_NAME = process.env.GITHUB_PAGES ? (process.env.GITHUB_REPOSITORY?.split('/')?.[1] ?? 'v0-fitness-exercise-website-3') : ''
const BASE = REPO_NAME ? `/${REPO_NAME}` : ''

export const exerciseDetails: Record<string, Record<string, any>> = {
  "boyun-sirt": {
    "boyun-germe": {
      title: "Boyun Germe Egzersizi",
      description:
        "Boyun kaslarını gevşetmek ve boyun ağrılarını azaltmak için yapılan temel germe egzersiz. Özellikle uzun süre bilgisayar başında çalışanlar için faydalıdır.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dik bir şekilde oturun veya ayakta durun",
        "Başınızı yavaşça sağa doğru eğin, kulağınızı omzunuza yaklaştırın",
        "15-30 saniye bu pozisyonda bekleyin",
        "Başınızı merkeze getirin ve sol tarafa tekrarlayın",
        "Hareket sırasında omuzlarınızı gevşek tutun",
      ],
      sets: 3,
      reps: "Her yöne 2",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Levator Scapulae", "Üst Trapezius", "Sternokleidomastoid"],
      warnings: ["Ani hareketlerden kaçının", "Ağrı hissederseniz durdurun", "Derin nefes almayı unutmayın"],
    },
    "kedi-deve": {
      title: "Kedi-Deve Hareketi",
      description: "Omurga esnekliğini artıran ve sırt kaslarını gevşeten yoga kökenli bir fizyoterapi egzersizi.",
      image: `${BASE}/placeholder.svg?height=600&width=800`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dört ayak üzerinde pozisyon alın (el ve dizler yerde)",
        "Ellerinizi omuz hizasında, dizlerinizi kalça hizasında yerleştirin",
        "Nefes vererek sırtınızı yukarı doğru kambur yapın (Kedi)",
        "Nefes alarak göğsünüzü öne itip sırtınızı aşağı doğru çökertin (Deve)",
        "Hareketi yavaş ve kontrollü şekilde tekrarlayın",
      ],
      sets: 2,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Abdominal Kaslar", "Torasik Omurga"],
      warnings: ["Boyun ve bel bölgesini aşırı zorlamayın", "Hareket akıcı olmalı"],
    },
    "skapula-sikma": {
      title: "Skapula Sıkma",
      description: "Skapular stabilizasyon için sırt kaslarını güçlendiren egzersiz.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      instructions: [
        "Dik oturun veya ayakta durun",
        "Kürek kemiklerinizi birbirine doğru sıkın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
        "Direnç bandı kullanarak zorluk artırılabilir",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Rhomboids", "Orta Trapezius", "Alt Trapezius"],
      warnings: ["Omuzları yukarı kaldırmayın", "Boyun gerginliği yapmayın"],
    },
    "torasik-rotasyon": {
      title: "Torasik Rotasyon",
      description: "Üst sırt mobilitesini artıran rotasyon egzersizi.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      instructions: [
        "Yan yatın, dizlerinizi bükerek fetal pozisyonda yatın",
        "Üstteki kolunuzu açarak arkaya döndürün",
        "Göğsünüzü tavana doğru açın",
        "15-20 saniye tutun",
        "Diğer tarafa dönüp tekrarlayın",
      ],
      sets: 3,
      reps: "Her taraf 5-8",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Torasik Omurga", "Rotator Kasları", "Pektoralis"],
      warnings: ["Ani hareketlerden kaçının", "Ağrı hissederseniz durdurun"],
    },
  },
  diz: {
    "kuadriseps-gucendirme": {
      title: "Kuadriseps Güçlendirme",
      description: "Diz stabilitesini artıran ve kuadriseps kasını güçlendiren temel rehabilitasyon egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Sandalyeye dik bir şekilde oturun",
        "Bir bacağınızı yavaşça düz bir şekilde kaldırın",
        "Ayak bileğinizi kendinize doğru çekin (dorsifleksiyon)",
        "Bacağınızı 5-10 saniye yukarıda tutun",
        "Yavaşça yere indirin ve diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Sandalye",
      targetMuscles: ["Kuadriseps (Rectus Femoris, Vastus Lateralis)", "Vastus Medialis"],
      warnings: ["Diz ağrısı hissedersinizse durdurun", "Hareket yavaş ve kontrollü olmalı"],
    },
    "duvara-oturma": {
      title: "Duvara Oturma (Wall Sit)",
      description: "Diz ve bacak kaslarını güçlendiren izometrik egzersiz. Diz stabilitesini artırır.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      instructions: [
        "Sırtınızı duvara yaslayın",
        "Ayaklarınızı omuz genişliğinde açın",
        "Dizleriniz 90 derece olacak şekilde aşağı doğru kayın",
        "Bu pozisyonda 20-30 saniye durun",
        "Yavaşça yukarı doğru çıkın",
      ],
      sets: 3,
      reps: "3-5",
      restTime: 60,
      difficulty: "Orta",
      equipment: "Duvar",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Dizleriniz ayak parmaklarınızı geçmemeli", "Ağrı hissederseniz durdurun"],
    },
    "hamstring-germe": {
      title: "Hamstring Germe",
      description: "Hamstring kaslarını uzatmak ve esnekliği artırmak için yapılan germe egzersizi.",
      image: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Sırt üstü yatın",
        "Bir bacağınızı kaldırın ve egzersiz bandını ayağınıza geçirin",
        "Bandı çekerek bacağınızı kendinize doğru getirin",
        "30 saniye tutun",
        "Diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "Her bacak 2",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Bandı",
      targetMuscles: ["Hamstring", "Gastroknemius"],
      warnings: ["Ani hareketlerden kaçının", "Aşırı zorlamayın"],
    },
    "step-up": {
      title: "Step Up",
      description: "Diz rehabilitasyonu için fonksiyonel güçlendirme egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      instructions: [
        "Step veya basamak önünde durun",
        "Bir ayağınızı step üzerine yerleştirin",
        "Diğer ayağınızı da yukarı çıkarın",
        "Kontrollü şekilde aşağı inin",
        "Alternatif bacaklarla tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Step/Basamak",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Dengeyi kaybederseniz destek kullanın", "Hareket kontrollü olmalı"],
    },
  },
  omuz: {
    sarkaç: {
      title: "Sarkaç Egzersizi (Pendulum)",
      description:
        "Omuz ağrıları ve donuk omuz için yapılan pasif hareket egzersizi. Omuz eklemini gevşetir ve hareket açıklığını artırır.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: [
        "Bir masaya yaslanarak öne doğru eğilin",
        "Sağlıklı kolunuzla masaya destek olun",
        "Ağrılı kolunuzu sarkıtın ve gevşetin",
        "Kolunuzu küçük daireler çizerek sallamaya başlayın",
        "Önce saat yönünde, sonra ters yönde çevirin",
        "Kaslarınızı gevşek tutun, ağırlık sallanımı sağlasın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Masa/Sandalye",
      targetMuscles: ["Rotator Cuff", "Deltoid", "Omuz Kapsülü"],
      warnings: ["Kas gücü kullanmayın, salınım pasif olmalı", "Ağrı artarsa durdurun"],
    },
    "duvar-tirmanisi": {
      title: "Duvar Tırmanışı (Wall Walk)",
      description: "Omuz hareket açıklığını artıran aktif egzersiz.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Duvara dönük olarak durun",
        "Parmaklarınızla duvarı tutun",
        "Parmaklarınızı yukarı doğru yürüterek kolunuzu kaldırın",
        "Maksimum yüksekliğe ulaştığınızda 5 saniye bekleyin",
        "Yavaşça aşağı inin",
      ],
      sets: 3,
      reps: "8-10",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Duvar",
      targetMuscles: ["Deltoid", "Rotator Cuff", "Serratus Anterior"],
      warnings: ["Ağrı hissederseniz durdurun", "Hareket yavaş olmalı"],
    },
    "omuz-rotasyonu": {
      title: "İç-Dış Rotasyon",
      description: "Rotator cuff kaslarını güçlendiren dirençli egzersiz.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Direnç bandını sabit bir yere bağlayın",
        "Dirseğinizi 90 derece büküp vücudunuza yakın tutun",
        "Bandı içe doğru çekerek iç rotasyon yapın",
        "Kontrollü şekilde geri dönün",
        "Dış rotasyon için pozisyonu değiştirin",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Infraspinatus", "Teres Minor", "Subscapularis"],
      warnings: ["Dirsek sabit kalmalı", "Aşırı ağırlık kullanmayın"],
    },
    "skapular-sikma": {
      title: "Skapular Sıkma",
      description: "Skapula stabilizasyonu için omuz bıçağı kaslarını güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Dik oturun veya ayakta durun",
        "Omuzlarınızı geriye doğru sıkın",
        "Kürek kemiklerinizi birbirine yaklaştırın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Rhomboids", "Trapezius", "Serratus Anterior"],
      warnings: ["Boyun gerginliği yapmayın", "Omuzları yukarı kaldırmayın"],
    },
  },
  bel: {
    "pelvik-tilt": {
      title: "Pelvik Tilt Egzersizi",
      description:
        "Bel ağrılarını azaltan ve core kaslarını aktive eden temel fizyoterapi hareketi. Lomber lordozis ve postür düzeltmede etkilidir.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırt üstü yatın, dizlerinizi bükerek ayaklarınızı yere koyun",
        "Kollarınızı yanlarınızda rahat bir pozisyonda tutun",
        "Alt karın kaslarınızı sıkarak bel bölgenizi yere bastırın",
        "5-10 saniye bu pozisyonda tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Transversus Abdominis", "Multifidus", "Pelvik Taban Kasları"],
      warnings: ["Nefes tutmayın", "Hareket küçük ve kontrollü olmalı"],
    },
    "kopru": {
      title: "Köprü Egzersizi (Bridge)",
      description: "Gluteal kasları ve alt sırtı güçlendiren temel egzersiz.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Sırt üstü yatın, dizlerinizi bükün",
        "Ayaklarınızı yere sıkıca basın",
        "Kalçanızı yukarı kaldırın",
        "Omuzdan dize kadar düz bir çizgi oluşturun",
        "5 saniye tutun ve yavaşça inin",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glutes", "Hamstring", "Erector Spinae"],
      warnings: ["Beli aşırı kambur yapmayın", "Core kasılanırınız tutun"],
    },
    "bird-dog": {
      title: "Bird Dog Egzersizi",
      description: "Core stabilizasyonu ve denge için kullanılan ileri seviye egzersiz.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Dört ayak üzerinde pozisyon alın",
        "Bir kolunuzu öne, karşı bacağınızı arkaya uzatın",
        "Kol ve bacak düz bir hat oluşturmalı",
        "5-10 saniye tutun",
        "Değiştirerek diğer tarafla tekrarlayın",
      ],
      sets: 3,
      reps: "8-10 her taraf",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Glutes", "Core Kasları"],
      warnings: ["Dengeyi kaybederseniz daha kısa tutun", "Sırtınızı düz tutun"],
    },
    "diz-gogus": {
      title: "Diz-Göğüs Germe",
      description: "Alt sırt kasını gevsi ve ağrıyı azaltan germe egzersizi.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Sırt üstü yatın",
        "Bir dizinizi göğsünüze doğru çekin",
        "Ellerinizle dizinizi tutun",
        "20-30 saniye bu pozisyonda kalın",
        "Diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "Her bacak 2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lomber Erector Spinae", "Glutes", "Piriformis"],
      warnings: ["Ani hareketlerden kaçının", "Ra gelmelidir"],
    },
  },
  "el-bilek": {
    "bilek-fleksiyonu": {
      title: "Bilek Fleksiyonu Egzersizi",
      description: "El bileği kaslarını güçlendiren ve karpal tünel sendromu tedavisinde kullanılan egzersiz.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: [
        "Önkolunuzu bir yüzeye yerleştirin, eli dışarıda bırakın",
        "Avucunuz yukarı bakacak şekilde pozisyon alın",
        "Hafif bir ağırlık tutun (veya ağırlıksız başlayın)",
        "Bileğinizi yukarı doğru kaldırın",
        "Yavaşça başlangıç pozisyonuna dönün",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Hafif Ağırlık (0.5-1 kg)",
      targetMuscles: ["Fleksor Karpi Radialis", "Fleksor Karpi Ulnaris"],
      warnings: ["Çok ağır ağırlık kullanmayın", "Ağrı hissederseniz durdurun"],
    },
    "parmak-germe": {
      title: "Parmak Germe Egzersizi",
      description: "Parmak kaslarını uzatmak ve esnekliği artırmak için.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Elinizi düz bir şekilde uzatın",
        "Diğer elinizle parmağınızı yavaşça geri çekin",
        "15-20 saniye tutun",
        "Her parmakla tekrarlayın",
        "Diğer elle de aynı işlemi yapın",
      ],
      sets: 2,
      reps: "Her parmak 1-2",
      restTime: 20,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Parmak Ekstansörleri", "Ele ve bilek kasları"],
      warnings: ["Aşırı zorlamayın", "Yavaş ve kontrollü çekin"],
    },
    "bilek-rotasyonu": {
      title: "Bilek Rotasyonu",
      description: "Bilek mobilitesini artıran dairesel hareket egzersizi.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Kolunuzu önünüzde tutun",
        "Bileğinizi yavaşça saat yönünde çevirin",
        "10 tekrar yapın",
        "Sonra ters yönde 10 tekrar",
        "Diğer bileğinizle tekrarlayın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Bilek Fleksörleri", "Bilek Ekstansörleri"],
      warnings: ["Hareket yumuşak olmalı", "Ağrı varsa durdurun"],
    },
    "kavrama-gucendirme": {
      title: "Kavrama Güçlendirme",
      description: "El kası gücünü artıran sıkma egzersizi.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Stres topu veya yumuşak top tutun",
        "Elinizle maksimum kuvvetle sıkın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
        "Her iki elle de yapın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Stres Topu",
      targetMuscles: ["Fleksör Dijitorum", "Thenar Kaslar"],
      warnings: ["El krampı olursa dinlenin", "Aşırı sıkmayın"],
    },
  },
  ayak: {
    "ayak-bileği-pumpa": {
      title: "Ayak Bileği Pompa Egzersizi",
      description:
        "Ayak bileği mobilitesini artıran ve şişliği azaltan temel egzersiz. Burkulma sonrası rehabilitasyonda kullanılır.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-pump-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırt üstü veya oturarak pozisyon alın",
        "Bacağınızı uzatın",
        "Ayak parmaklarınızı kendinize doğru çekin",
        "Sonra ayak parmaklarınızı öne doğru uzatın",
        "Hareketi ritmik bir şekilde tekrarlayın",
      ],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Tibialis Anterior", "Gastroknemius", "Soleus"],
      warnings: ["Hareket yumuşak olmalı", "Kramp hissederseniz dinlenin"],
    },
    "havlu-toplama": {
      title: "Havlu Toplama Egzersizi",
      description: "Ayak kemer kaslarını güçlendiren fonksiyonel egzersiz.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Bir havluyu yere yayın",
        "Ayaklarınızla havluyu toplamaya çalışın",
        "Parmaklarınızı kullanarak havluyu çekin",
        "Havlunun tamamını topladığınızda tekrar açın",
        "Her iki ayakla da yapın",
      ],
      sets: 3,
      reps: "5-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Havlu",
      targetMuscles: ["Ayak Kemer Kasları", "Fleksor Digitorum Brevis"],
      warnings: ["Kramp olursa dinlenin", "Yavaş başlayın"],
    },
    "ayak-bileği-rotasyonu": {
      title: "Ayak Bileği Rotasyonu",
      description: "Ayak bileği mobilitesini artıran dairesel hareket.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Oturarak bir bacağınızı kaldırın",
        "Ayak bileğinizi saat yönünde çevirin",
        "10 tekrar yapın",
        "Ters yönde 10 tekrar",
        "Diğer ayakla tekrarlayın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Ayak Bileği Stabilizatörleri", "Peroneal Kaslar"],
      warnings: ["Hareket yumuşak olmalı", "Ağrı varsa durdurun"],
    },
    "topuk-yukseltme": {
      title: "Topuk Yükseltme (Calf Raise)",
      description: "Baldyr kaslarını güçlendiren egzersiz.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Duvara veya sandalyeye destek olarak durun",
        "Parmak uçlarınıza kalkın",
        "Topuklarınızı maksimum yüksekliğe kaldırın",
        "2 saniye tutun",
        "Yavaşça inin ve tekrarlayın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Duvar/Sandalye",
      targetMuscles: ["Gastroknemius", "Soleus"],
      warnings: ["Denge için destek kullanın", "Ayak bileği ağrısı varsa durdurun"],
    },
  },
}
