const REPO_NAME = process.env.GITHUB_PAGES ? (process.env.GITHUB_REPOSITORY?.split('/')?.[1] ?? 'v0-fitness-exercise-website-3') : ''
const BASE = REPO_NAME ? `/${REPO_NAME}` : ''

export const exerciseDetails: Record<string, Record<string, any>> = {
  "boyun-sirt": {
    "boyun-germe": {
      title: "Boyun Germe Egzersizi",
      description:
        "Boyun kaslarını gevşetmek ve boyun ağrılarını azaltmak için yapılan temel germe egzersiz. Özellikle uzun süre bilgisayar başında çalışanlar için faydalıdır.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dik bir şekilde oturun veya ayakta durun",
        "Başınızı yavaşça sağa doğru eğin, kulağınızı omzunuza yaklaştırın",
        "15-30 saniye bu pozisyonda bekleyin",
        "Başınızı merkeze getirin ve sol tarafa tekrarlayın",
        "Hareket sırasında omuzlarınızı gevşek tutun",
      ],
      sets: 3,
      reps: "Her yöne 2",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Levator Scapulae", "Üst Trapezius", "Sternokleidomastoid"],
      warnings: ["Ani hareketlerden kaçının", "Ağrı hissederseniz durdurun", "Derin nefes almayı unutmayın"],
    },
    "kedi-deve": {
      title: "Kedi-Deve Hareketi",
      description: "Omurga esnekliğini artıran ve sırt kaslarını gevşeten yoga kökenli bir fizyoterapi egzersizi.",
      image: `${BASE}/placeholder.svg?height=600&width=800`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dört ayak üzerinde pozisyon alın (el ve dizler yerde)",
        "Ellerinizi omuz hizasında, dizlerinizi kalça hizasında yerleştirin",
        "Nefes vererek sırtınızı yukarı doğru kambur yapın (Kedi)",
        "Nefes alarak göğsünüzü öne itip sırtınızı aşağı doğru çökertin (Deve)",
        "Hareketi yavaş ve kontrollü şekilde tekrarlayın",
      ],
      sets: 2,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Abdominal Kaslar", "Torasik Omurga"],
      warnings: ["Boyun ve bel bölgesini aşırı zorlamayın", "Hareket akıcı olmalı"],
    },
    "skapula-sikma": {
      title: "Skapula Sıkma",
      description: "Skapular stabilizasyon için sırt kaslarını güçlendiren egzersiz.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      instructions: [
        "Dik oturun veya ayakta durun",
        "Kürek kemiklerinizi birbirine doğru sıkın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
        "Direnç bandı kullanarak zorluk artırılabilir",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Rhomboids", "Orta Trapezius", "Alt Trapezius"],
      warnings: ["Omuzları yukarı kaldırmayın", "Boyun gerginliği yapmayın"],
    },
    "torasik-rotasyon": {
      title: "Torasik Rotasyon",
      description: "Üst sırt mobilitesini artıran rotasyon egzersizi.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      instructions: [
        "Yan yatın, dizlerinizi bükerek fetal pozisyonda yatın",
        "Üstteki kolunuzu açarak arkaya döndürün",
        "Göğsünüzü tavana doğru açın",
        "15-20 saniye tutun",
        "Diğer tarafa dönüp tekrarlayın",
      ],
      sets: 3,
      reps: "Her taraf 5-8",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Torasik Omurga", "Rotator Kasları", "Pektoralis"],
      warnings: ["Ani hareketlerden kaçının", "Ağrı hissederseniz durdurun"],
    },
    "boyun-izometrik": {
      title: "Boyun İzometrik Güçlendirme",
      description: "Boyun kaslarını güçlendirmek için direnç egzersizi.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dik oturun, alnınıza elinizi yerleştirin",
        "Başınızı öne itmeden elinize karşı bastırın",
        "5-10 saniye tutun",
        "Başınızın yan tarafı ve arkası için tekrarlayın",
        "Hareket sırasında nefes almaya devam edin",
      ],
      sets: 3,
      reps: "Her yön 8-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Sternocleidomastoid", "Boyun Fleksörleri", "Boyun Ekstansörleri"],
      warnings: ["Aşırı kuvvet uygulamayın", "Boyun ağrısı varsa hafif başlayın"],
    },
    "chin-tuck": {
      title: "Chin Tuck (Çene Çekme)",
      description: "Boyun postürünü düzeltmek için yapılan egzersiz.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Dik oturun veya durun",
        "Çenenizi geriye doğru çekin (çift çene yapar gibi)",
        "Başınız aynı seviyede kalmalı",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Derin Boyun Fleksörleri", "Servikal Stabilizatörler"],
      warnings: ["Başı eğmeyin", "Sadece çeneyi geriye çekin"],
    },
    "sirt-ust-germe": {
      title: "Üst Sırt Germe",
      description: "Sırt üst kısmındaki gerginliği azaltan germe egzersizi.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Ayakta durun, ellerinizi önünüzde birleştirin",
        "Kollarınızı öne doğru uzatın",
        "Sırtınızı yuvarlayın ve omuz bıçaklarını ayırın",
        "20-30 saniye tutun",
        "Derin nefes alın",
      ],
      sets: 3,
      reps: "3-4",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Rhomboids", "Trapezius", "Latissimus Dorsi"],
      warnings: ["Omuzlarda ağrı varsa durdurun"],
    },
    "duvar-melek": {
      title: "Duvar Meleği (Wall Angels)",
      description: "Omuz ve sırt postürünü düzelten hareket.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırtınızı duvara yaslayın",
        "Kollarınızı 90 derece büküp duvara değdirin",
        "Kolları yukarı ve aşağı hareket ettirin",
        "Dirsekler ve eller her zaman duvarda kalmalı",
        "10-12 tekrar yapın",
      ],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Duvar",
      targetMuscles: ["Trapezius", "Serratus Anterior", "Rotator Cuff"],
      warnings: ["Bel boşluğu çok fazla olmamalı"],
    },
    "trapez-germe": {
      title: "Trapez Kas Germe",
      description: "Üst trapez kasını rahatlatma egzersizi.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Oturun, bir elinizi sırtınızın arkasına koyun",
        "Diğer elinizle başınızı karşı tarafa eğin",
        "Hafif çekerek germe hissedin",
        "20-30 saniye tutun",
        "Her iki taraf için tekrarlayın",
      ],
      sets: 3,
      reps: "Her taraf 2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Üst Trapezius", "Levator Scapulae"],
      warnings: ["Aşırı çekmeyin", "Yumuşak ve kontrollü olmalı"],
    },
    "omuz-cemberler": {
      title: "Omuz Çemberleri",
      description: "Omuz mobilites ve kan dolaşımını artırma.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Ayakta veya oturarak başlayın",
        "Omuzlarınızı daire çizerek döndürün",
        "İleri yönde 10, geri yönde 10 tekrar",
        "Hareket geniş ve kontrollü olmalı",
        "Boyun rahat kalmalı",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Deltoid", "Trapezius", "Rotator Cuff"],
      warnings: ["Ağrı hissederseniz durdurun"],
    },
    "skapula-retraksiyon": {
      title: "Skapula Retraksiyon",
      description: "Omuz bıçaklarını geriye çekme egzersizi.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Direnç bandı tutun veya ağırlıksız yapın",
        "Kolları önde, dirsekler hafif bükük",
        "Omuz bıçaklarını birbirine yaklaştırın",
        "2-3 saniye tutun",
        "Yavaşça gevşetin",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı (Opsiyonel)",
      targetMuscles: ["Rhomboids", "Mid Trapezius"],
      warnings: ["Omuzları yukarı kaldırmayın"],
    },
    "cobra-germe": {
      title: "Cobra Germe",
      description: "Sırt ekstansörlerini güçlendirme ve göğüs açma.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Yüzüstü yatın, eller omuz hizasında",
        "Elleri yere bastırarak göğsü kaldırın",
        "Kalça yerde kalmalı",
        "10-15 saniye tutun",
        "Yavaşça inin",
      ],
      sets: 3,
      reps: "8-10",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Multifidus"],
      warnings: ["Bel ağrısı varsa dikkatli olun"],
    },
    "y-t-w": {
      title: "Y-T-W Egzersizi",
      description: "Skapular stabilizasyon için üç pozisyonlu egzersiz.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Yüzüstü yatın veya eğimli bankta durun",
        "Y pozisyonu: Kolları yukarı çapraz",
        "T pozisyonu: Kollar yanlara",
        "W pozisyonu: Dirsekler 90 derece",
        "Her pozisyonda 5 saniye tutun",
      ],
      sets: 3,
      reps: "8-10 her pozisyon",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Trapezius", "Rhomboids", "Posterior Deltoid"],
      warnings: ["Ağırlık kullanıyorsanız hafif başlayın"],
    },
    "sirt-ext": {
      title: "Sırt Ekstansiyon",
      description: "Alt sırt ekstansörlerini güçlendirme.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Yüzüstü yatın, eller başın yanında",
        "Üst gövdeyi yerden kaldırın",
        "3-5 saniye tutun",
        "Kontrollü şekilde inin",
        "Boyun nötr pozisyonda",
      ],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Multifidus", "Gluteus"],
      warnings: ["Aşırı kambur yapmayın"],
    },
    "torasik-kopru": {
      title: "Torasik Köprü",
      description: "Üst sırt mobilizasyonu için köprü varyasyonu.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırtüstü yatın, dizler bükük",
        "Foam roller torasik bölgeye yerleştirin",
        "Kalçayı kaldırıp roller üzerinde ileri geri",
        "10-15 tekrar",
        "Hassas noktaları bulup 30 sn bekleyin",
      ],
      sets: 2,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Foam Roller",
      targetMuscles: ["Torasik Omurga", "Paraspinal Kaslar"],
      warnings: ["Boyun ve bel bölgesinde kullanmayın"],
    },
    "superman": {
      title: "Superman Egzersizi",
      description: "Tüm sırt zincirini güçlendirme.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Yüzüstü yatın, kol ve bacaklar uzun",
        "Aynı anda kol ve bacakları kaldırın",
        "3-5 saniye havada tutun",
        "Yavaşça inin",
        "Nefes almaya devam edin",
      ],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Gluteus", "Hamstring"],
      warnings: ["Boyun gergin kalmamalı"],
    },
    "boyun-yan-germe": {
      title: "Boyun Yan Germe",
      description: "Boyun yan kaslarını gevşetme.",
      image: `${BASE}/neck-stretching-exercise-physiotherapy.jpg`,
      video: `${BASE}/neck-stretching-exercise-demonstration-animation.jpg`,
      instructions: [
        "Oturun veya ayakta durun",
        "Başı bir yana eğin",
        "Karşı omuz aşağıda kalmalı",
        "20-30 saniye tutun",
        "Her iki taraf için tekrarlayın",
      ],
      sets: 3,
      reps: "Her taraf 2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Scalene Kasları", "Levator Scapulae"],
      warnings: ["Yumuşak ve yavaş olmalı"],
    },
    "prone-row": {
      title: "Prone Row (Yüzüstü Kürek)",
      description: "Sırt kaslarını güçlendiren kürek hareketi.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Yüzüstü yatın, alın yerde",
        "Kolları yana açık, dirsekler 90 derece",
        "Dirsekleri yukarı kaldırın",
        "Omuz bıçaklarını sıkın",
        "2-3 saniye tutun ve inin",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Rhomboids", "Mid Trapezius", "Rear Deltoid"],
      warnings: ["Boyun rahat kalmalı"],
    },
    "skapula-push-up": {
      title: "Skapular Push-Up",
      description: "Omuz bıçağı stabilitesi için şınav varyasyonu.",
      image: `${BASE}/cat-cow-stretch-yoga-mat-physiotherapy.jpg`,
      video: `${BASE}/cat-cow-exercise-demonstration-animation.jpg`,
      instructions: [
        "Plank pozisyonunda başlayın",
        "Kollar düz kalacak şekilde",
        "Sadece omuz bıçaklarını hareket ettirin",
        "Sırtı yukarı iterken bıçaklar ayrılır",
        "Sonra bıçakları birbirine yaklaştırın",
      ],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Serratus Anterior", "Pectoralis Minor"],
      warnings: ["Core sıkı tutun", "Bel çökmesin"],
    },
  },
  diz: {
    "kuadriseps-gucendirme": {
      title: "Kuadriseps Güçlendirme",
      description: "Diz stabilitesini artıran ve kuadriseps kasını güçlendiren temel rehabilitasyon egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Sandalyeye dik bir şekilde oturun",
        "Bir bacağınızı yavaşça düz bir şekilde kaldırın",
        "Ayak bileğinizi kendinize doğru çekin (dorsifleksiyon)",
        "Bacağınızı 5-10 saniye yukarıda tutun",
        "Yavaşça yere indirin ve diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Sandalye",
      targetMuscles: ["Kuadriseps (Rectus Femoris, Vastus Lateralis)", "Vastus Medialis"],
      warnings: ["Diz ağrısı hissedersinizse durdurun", "Hareket yavaş ve kontrollü olmalı"],
    },
    "duvara-oturma": {
      title: "Duvara Oturma (Wall Sit)",
      description: "Diz ve bacak kaslarını güçlendiren izometrik egzersiz. Diz stabilitesini artırır.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      instructions: [
        "Sırtınızı duvara yaslayın",
        "Ayaklarınızı omuz genişliğinde açın",
        "Dizleriniz 90 derece olacak şekilde aşağı doğru kayın",
        "Bu pozisyonda 20-30 saniye durun",
        "Yavaşça yukarı doğru çıkın",
      ],
      sets: 3,
      reps: "3-5",
      restTime: 60,
      difficulty: "Orta",
      equipment: "Duvar",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Dizleriniz ayak parmaklarınızı geçmemeli", "Ağrı hissederseniz durdurun"],
    },
    "hamstring-germe": {
      title: "Hamstring Germe",
      description: "Hamstring kaslarını uzatmak ve esnekliği artırmak için yapılan germe egzersizi.",
      image: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Sırt üstü yatın",
        "Bir bacağınızı kaldırın ve egzersiz bandını ayağınıza geçirin",
        "Bandı çekerek bacağınızı kendinize doğru getirin",
        "30 saniye tutun",
        "Diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "Her bacak 2",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Bandı",
      targetMuscles: ["Hamstring", "Gastroknemius"],
      warnings: ["Ani hareketlerden kaçının", "Aşırı zorlamayın"],
    },
    "step-up": {
      title: "Step Up",
      description: "Diz rehabilitasyonu için fonksiyonel güçlendirme egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      instructions: [
        "Step veya basamak önünde durun",
        "Bir ayağınızı step üzerine yerleştirin",
        "Diğer ayağınızı da yukarı çıkarın",
        "Kontrollü şekilde aşağı inin",
        "Alternatif bacaklarla tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Step/Basamak",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Dengeyi kaybederseniz destek kullanın", "Hareket kontrollü olmalı"],
    },
    "tek-bacak-squat": {
      title: "Tek Bacak Squat",
      description: "Diz stabilitesi ve denge için ileri seviye egzersiz.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Bir ayak üzerinde durun",
        "Diğer bacağı önde tutun",
        "Yavaşça dizinizi bükerek çömelin",
        "Kontrollü şekilde kalkın",
        "Her bacak için tekrarlayın",
      ],
      sets: 3,
      reps: "8-10 her bacak",
      restTime: 45,
      difficulty: "İleri",
      equipment: "Ekipman Yok",
      targetMuscles: ["Kuadriseps", "Glutes", "Core"],
      warnings: ["Destek kullanın", "Diz ağrısı varsa durdurun"],
    },
    "terminal-knee-extension": {
      title: "Terminal Knee Extension",
      description: "VMO kasını hedefleyen izolasyon egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Direnç bandı dizin arkasına yerleştirin",
        "Dizinizi hafif bükük başlayın",
        "Dizinizi tam olarak düzeltin",
        "2-3 saniye tutun",
        "Yavaşça geri dönün",
      ],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Vastus Medialis Obliquus", "Kuadriseps"],
      warnings: ["Aşırı zorlama yapmayın"],
    },
    "lateral-step-down": {
      title: "Lateral Step Down",
      description: "Diz kontrolü ve stabilite egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Düşük bir step üzerinde yan durun",
        "Dış ayağı yavaşça yere indirin",
        "Diziniz kontrollü hareket etmeli",
        "Geri çıkın ve tekrarlayın",
        "Her bacak için yapın",
      ],
      sets: 3,
      reps: "10-12 her bacak",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Step",
      targetMuscles: ["Kuadriseps", "Glute Medius", "Stabilizatörler"],
      warnings: ["Diz içe kaymamalı"],
    },
    "clamshell": {
      title: "Clamshell Egzersizi",
      description: "Kalça abduktörlerini güçlendirme.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Yan yatın, dizler bükük",
        "Ayaklar bir arada",
        "Üst dizi yukarı kaldırın",
        "2 saniye tutun",
        "Yavaşça inin",
      ],
      sets: 3,
      reps: "15-20 her taraf",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı (Opsiyonel)",
      targetMuscles: ["Glute Medius", "Glute Minimus"],
      warnings: ["Kalça geriye gitmesin"],
    },
    "monster-walk": {
      title: "Monster Walk",
      description: "Kalça ve diz stabilizasyonu için bant egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Direnç bandını dizlerin üstüne takın",
        "Hafif çömelmiş pozisyonda",
        "Yan yan adımlarla yürüyün",
        "Dizler dışa dönük kalmalı",
        "10 adım her yöne",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Glutes", "Hip Abductors", "Kuadriseps"],
      warnings: ["Dizler içe kapanmasın"],
    },
    "leg-press-tek-bacak": {
      title: "Tek Bacak Leg Press",
      description: "Unilateral bacak güçlendirme.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Leg press makinesinde oturun",
        "Tek ayağı platforma yerleştirin",
        "Dizinizi kontrollü büküp açın",
        "Tam kilit yapmayın",
        "Her bacak için tekrarlayın",
      ],
      sets: 3,
      reps: "10-12 her bacak",
      restTime: 60,
      difficulty: "Orta",
      equipment: "Leg Press Makinesi",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Ağır başlamayın"],
    },
    "bulgarian-split-squat": {
      title: "Bulgarian Split Squat",
      description: "İleri seviye tek bacak squat varyasyonu.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Arka ayağı yükseltilmiş yüzeyde",
        "Ön bacakla çömelin",
        "Diz 90 derece olana kadar",
        "Topuktan iterek kalkın",
        "Her bacak için tekrarlayın",
      ],
      sets: 3,
      reps: "10-12 her bacak",
      restTime: 60,
      difficulty: "İleri",
      equipment: "Bench",
      targetMuscles: ["Kuadriseps", "Glutes", "Hamstring"],
      warnings: ["Denge için destek kullanın"],
    },
    "seated-knee-flexion": {
      title: "Oturarak Diz Fleksiyonu",
      description: "Hamstring izolasyonu egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Sandalyeye oturun",
        "Bandı ayağınıza bağlayın",
        "Dizinizi bükerek topuğu geriye çekin",
        "2 saniye tutun",
        "Yavaşça uzatın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Hamstring", "Gastroknemius"],
      warnings: ["Kalça hareket etmesin"],
    },
    "side-lying-leg-lift": {
      title: "Yan Yatarak Bacak Kaldırma",
      description: "Hip abduktor güçlendirme.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Yan yatın, alt bacak bükük",
        "Üst bacağı düz tutun",
        "Bacağı yukarı kaldırın",
        "2 saniye tutun",
        "Yavaşça indirin",
      ],
      sets: 3,
      reps: "15-20 her taraf",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glute Medius", "TFL"],
      warnings: ["Kalça öne gitmesin"],
    },
    "nordic-hamstring-curl": {
      title: "Nordic Hamstring Curl",
      description: "İleri seviye hamstring güçlendirme.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Dizler yerde, ayaklar sabitlenmiş",
        "Vücudu yavaşça öne doğru indirin",
        "Hamstring kontrolü ile",
        "Ellere hafifçe tutunarak kalkın",
        "Çok zor ise daha az inin",
      ],
      sets: 3,
      reps: "5-8",
      restTime: 90,
      difficulty: "İleri",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Hamstring"],
      warnings: ["Çok zor, dikkatli başlayın"],
    },
    "reverse-lunge": {
      title: "Reverse Lunge (Geri Adım)",
      description: "Diz dostu lunge varyasyonu.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "Ayakta dik durun",
        "Bir bacağı geriye atın",
        "Her iki diz 90 derece olana kadar inin",
        "Ön topuktan iterek dönün",
        "Alternatif bacaklarla",
      ],
      sets: 3,
      reps: "10-12 her bacak",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Ekipman Yok",
      targetMuscles: ["Kuadriseps", "Glutes"],
      warnings: ["Ön diz ayak parmağını geçmesin"],
    },
    "glute-bridge-tek-bacak": {
      title: "Tek Bacak Glute Bridge",
      description: "Unilateral kalça ve hamstring güçlendirme.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Sırtüstü yatın, bir diz bükük",
        "Diğer bacak düz yukarıda",
        "Kalçayı yukarı iterken bükük bacakla",
        "3 saniye tutun",
        "Yavaşça indirin",
      ],
      sets: 3,
      reps: "10-12 her bacak",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glutes", "Hamstring", "Core"],
      warnings: ["Bel arkı yapmasın"],
    },
    "lateral-band-walk": {
      title: "Lateral Band Walk",
      description: "Kalça abduktor aktivasyonu.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Ayak bileklerine bant takın",
        "Hafif squat pozisyonunda",
        "Yana doğru adımlarla yürüyün",
        "Dizler dışarıda kalmalı",
        "10 adım her yöne",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Glute Medius", "TFL"],
      warnings: ["Üst vücut dik durmalı"],
    },
    "pistol-squat-assisted": {
      title: "Destekli Pistol Squat",
      description: "Tek bacak squat progresyonu.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/quadriceps-strengthening-exercise-demonstration.jpg`,
      instructions: [
        "TRX veya ip tutun",
        "Bir bacak havada düz",
        "Tek bacakla tam çömelin",
        "Destek ile kalkın",
        "Her bacak için tekrarlayın",
      ],
      sets: 3,
      reps: "6-8 her bacak",
      restTime: 60,
      difficulty: "İleri",
      equipment: "TRX/İp",
      targetMuscles: ["Kuadriseps", "Glutes", "Core"],
      warnings: ["İlk kez yapıyorsanız destek kullanın"],
    },
    "prone-hamstring-curl": {
      title: "Yüzüstü Hamstring Curl",
      description: "Hamstring izolasyon egzersizi.",
      image: `${BASE}/knee-rehabilitation-exercises-physical-therapy.jpg`,
      video: `${BASE}/hamstring-stretch-resistance-band-therapy.jpg`,
      instructions: [
        "Yüzüstü yatın",
        "Ayak bileğine ağırlık veya bant",
        "Topuğu kalçaya doğru çekin",
        "2 saniye tutun",
        "Yavaşça uzatın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ağırlık/Bant",
      targetMuscles: ["Hamstring"],
      warnings: ["Kalça yerde kalmalı"],
    },
  },
  omuz: {
    sarkac: {
      title: "Sarkaç Egzersizi (Pendulum)",
      description:
        "Omuz ağrıları ve donuk omuz için yapılan pasif hareket egzersizi. Omuz eklemini gevşetir ve hareket açıklığını artırır.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: [
        "Bir masaya yaslanarak öne doğru eğilin",
        "Sağlıklı kolunuzla masaya destek olun",
        "Ağrılı kolunuzu sarkıtın ve gevşetin",
        "Kolunuzu küçük daireler çizerek sallamaya başlayın",
        "Önce saat yönünde, sonra ters yönde çevirin",
        "Kaslarınızı gevşek tutun, ağırlık sallanımı sağlasın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Masa/Sandalye",
      targetMuscles: ["Rotator Cuff", "Deltoid", "Omuz Kapsülü"],
      warnings: ["Kas gücü kullanmayın, salınım pasif olmalı", "Ağrı artarsa durdurun"],
    },
    "duvar-tirmanisi": {
      title: "Duvar Tırmanışı (Wall Walk)",
      description: "Omuz hareket açıklığını artıran aktif egzersiz.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Duvara dönük olarak durun",
        "Parmaklarınızla duvarı tutun",
        "Parmaklarınızı yukarı doğru yürüterek kolunuzu kaldırın",
        "Maksimum yüksekliğe ulaştığınızda 5 saniye bekleyin",
        "Yavaşça aşağı inin",
      ],
      sets: 3,
      reps: "8-10",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Duvar",
      targetMuscles: ["Deltoid", "Rotator Cuff", "Serratus Anterior"],
      warnings: ["Ağrı hissederseniz durdurun", "Hareket yavaş olmalı"],
    },
    "omuz-rotasyonu": {
      title: "İç-Dış Rotasyon",
      description: "Rotator cuff kaslarını güçlendiren dirençli egzersiz.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Direnç bandını sabit bir yere bağlayın",
        "Dirseğinizi 90 derece büküp vücudunuza yakın tutun",
        "Bandı içe doğru çekerek iç rotasyon yapın",
        "Kontrollü şekilde geri dönün",
        "Dış rotasyon için pozisyonu değiştirin",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Infraspinatus", "Teres Minor", "Subscapularis"],
      warnings: ["Dirsek sabit kalmalı", "Aşırı ağırlık kullanmayın"],
    },
    "skapular-sikma": {
      title: "Skapular Sıkma",
      description: "Skapula stabilizasyonu için omuz bıçağı kaslarını güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      instructions: [
        "Dik oturun veya ayakta durun",
        "Omuzlarınızı geriye doğru sıkın",
        "Kürek kemiklerinizi birbirine yaklaştırın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Rhomboids", "Trapezius", "Serratus Anterior"],
      warnings: ["Boyun gerginliği yapmayın", "Omuzları yukarı kaldırmayın"],
    },
    "face-pull": {
      title: "Face Pull",
      description: "Arka deltoid ve rotator cuff güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Yüksek pozisyonda ip tutun", "Yüzünüze doğru çekin", "Dirsekler yüksekte", "Omuz bıçaklarını sıkın", "Yavaşça geri"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Kablo/Bant",
      targetMuscles: ["Rear Deltoid", "Rotator Cuff", "Rhomboids"],
      warnings: ["Omuzları yukarı kaldırmayın"],
    },
    "band-pull-apart": {
      title: "Band Pull Apart",
      description: "Skapular retraksiyon ve posterior omuz.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Bandı önde tutun", "Kolları iki yana açın", "Göğsü açın", "2 saniye tutun", "Kontrollü geri"],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Direnç Bandı",
      targetMuscles: ["Rhomboids", "Rear Deltoid"],
      warnings: ["Dirsekler hafif bükük"],
    },
    "lateral-raise": {
      title: "Lateral Raise",
      description: "Yan deltoid izolasyonu.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Hafif dumbbells tutun", "Kolları yana kaldırın", "Omuz hizasına kadar", "2 saniye tutun", "Kontrollü indirin"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Lateral Deltoid"],
      warnings: ["Çok ağır kullanmayın"],
    },
    "front-raise": {
      title: "Front Raise",
      description: "Ön deltoid güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Dumbbells önde", "Kolları öne kaldırın", "Göz hizasına", "Kontrollü indirin", "Alternatif olarak yapılabilir"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Anterior Deltoid"],
      warnings: ["Momentum kullanmayın"],
    },
    "reverse-fly": {
      title: "Reverse Fly",
      description: "Arka deltoid ve skapular kaslar.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Öne eğilin", "Dumbbells tutun", "Kolları yana açın", "Omuz bıçaklarını sıkın", "Yavaşça indirin"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Rear Deltoid", "Rhomboids"],
      warnings: ["Bel düz kalmalı"],
    },
    "scaption": {
      title: "Scaption",
      description: "Skapular plane kaldırma.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Kolları 30 derece önde", "Thumbs up pozisyonu", "Omuz hizasına kaldırın", "Kontrollü indirin", "Skapula stabil"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Supraspinatus", "Deltoid"],
      warnings: ["Hafif ağırlık kullanın"],
    },
    "overhead-press": {
      title: "Overhead Press",
      description: "Omuz genel güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Dumbbells omuz hizasında", "Yukarı itin", "Kolları tam açın", "Kontrollü indirin", "Core sıkı"],
      sets: 3,
      reps: "10-12",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Deltoid", "Triceps"],
      warnings: ["Bel arkı yapmasın"],
    },
    "arnold-press": {
      title: "Arnold Press",
      description: "Rotasyonlu omuz press.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Önde palms facing", "Press yaparken rotate edin", "Yukarıda palms forward", "Geri dönerken rotate", "Kontrollü hareket"],
      sets: 3,
      reps: "10-12",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Deltoid", "Rotator Cuff"],
      warnings: ["Ağır başlamayın"],
    },
    "cuban-rotation": {
      title: "Cuban Rotation",
      description: "Rotator cuff mobilite ve güç.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Dumbbells ile upright row", "Dirsekler yukarıda", "Ön kola rotate edin", "Overhead position", "Reverse the movement"],
      sets: 3,
      reps: "10-12",
      restTime: 45,
      difficulty: "İleri",
      equipment: "Dumbbells",
      targetMuscles: ["Rotator Cuff", "Deltoid"],
      warnings: ["Hafif ağırlık, kontrollü"],
    },
    "sleeper-stretch": {
      title: "Sleeper Stretch",
      description: "İç rotasyon germe.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Yan yatın, alt kol 90 derece", "Üst elle ön kolu bastırın", "İç rotasyon germe", "30 saniye tutun", "Her taraf"],
      sets: 3,
      reps: "2-3 her taraf",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Posterior Capsule"],
      warnings: ["Yumuşak germe"],
    },
    "doorway-stretch": {
      title: "Doorway Pec Stretch",
      description: "Göğüs germe postür için.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Kapı pervazında kollar", "Öne doğru adım", "Göğüste germe hissi", "30 saniye tutun", "Derin nefes"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Kapı",
      targetMuscles: ["Pectoralis"],
      warnings: ["Aşırı zorlamayın"],
    },
    "hanging-shrug": {
      title: "Hanging Shrug",
      description: "Skapular depresyon güçlendirme.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Bardan asılın", "Omuzları yukarı çekin", "Sonra aşağı basın", "Skapular kontrol", "10-15 saniye hold"],
      sets: 3,
      reps: "8-10",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Pull-up Bar",
      targetMuscles: ["Lower Trapezius", "Serratus"],
      warnings: ["Grip gücü gerekir"],
    },
    "prone-t-raise": {
      title: "Prone T-Raise",
      description: "Mid trapezius izolasyonu.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Yüzüstü yatın", "Kollar T pozisyonunda", "Thumbs up", "Kolları kaldırın", "2 saniye tutun"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Mid Trapezius"],
      warnings: ["Hafif veya ağırlıksız"],
    },
    "blackburn-y": {
      title: "Blackburn Y Exercise",
      description: "Lower trapezius aktivasyonu.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Yüzüstü, kollar Y şeklinde", "Thumbs up", "Kolları kaldırın", "3 saniye hold", "Yavaşça indirin"],
      sets: 3,
      reps: "10-12",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lower Trapezius", "Serratus"],
      warnings: ["Boyun rahat"],
    },
    "plank-tap": {
      title: "Plank Shoulder Tap",
      description: "Skapular stabilite ve core.",
      image: `${BASE}/pendulum-shoulder-exercise-physiotherapy.jpg`,
      video: `${BASE}/shoulder-pendulum-exercise-demonstration-animation.jpg`,
      instructions: ["Plank pozisyonunda", "Bir el karşı omuza", "Minimal rotation", "Alternatif taraflar", "Kontrol önemli"],
      sets: 3,
      reps: "10 her taraf",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Serratus", "Core"],
      warnings: ["Kalça stabil"],
    },
  },
  bel: {
    "pelvik-tilt": {
      title: "Pelvik Tilt Egzersizi",
      description:
        "Bel ağrılarını azaltan ve core kaslarını aktive eden temel fizyoterapi hareketi. Lomber lordozis ve postür düzeltmede etkilidir.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırt üstü yatın, dizlerinizi bükerek ayaklarınızı yere koyun",
        "Kollarınızı yanlarınızda rahat bir pozisyonda tutun",
        "Alt karın kaslarınızı sıkarak bel bölgenizi yere bastırın",
        "5-10 saniye bu pozisyonda tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Transversus Abdominis", "Multifidus", "Pelvik Taban Kasları"],
      warnings: ["Nefes tutmayın", "Hareket küçük ve kontrollü olmalı"],
    },
    "kopru": {
      title: "Köprü Egzersizi (Bridge)",
      description: "Gluteal kasları ve alt sırtı güçlendiren temel egzersiz.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Sırt üstü yatın, dizlerinizi bükün",
        "Ayaklarınızı yere sıkıca basın",
        "Kalçanızı yukarı kaldırın",
        "Omuzdan dize kadar düz bir çizgi oluşturun",
        "5 saniye tutun ve yavaşça inin",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glutes", "Hamstring", "Erector Spinae"],
      warnings: ["Beli aşırı kambur yapmayın", "Core kasılanırınız tutun"],
    },
    "bird-dog": {
      title: "Bird Dog Egzersizi",
      description: "Core stabilizasyonu ve denge için kullanılan ileri seviye egzersiz.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Dört ayak üzerinde pozisyon alın",
        "Bir kolunuzu öne, karşı bacağınızı arkaya uzatın",
        "Kol ve bacak düz bir hat oluşturmalı",
        "5-10 saniye tutun",
        "Değiştirerek diğer tarafla tekrarlayın",
      ],
      sets: 3,
      reps: "8-10 her taraf",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Glutes", "Core Kasları"],
      warnings: ["Dengeyi kaybederseniz daha kısa tutun", "Sırtınızı düz tutun"],
    },
    "diz-gogus": {
      title: "Diz-Göğüs Germe",
      description: "Alt sırt kasını gevsi ve ağrıyı azaltan germe egzersizi.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: [
        "Sırt üstü yatın",
        "Bir dizinizi göğsünüze doğru çekin",
        "Ellerinizle dizinizi tutun",
        "20-30 saniye bu pozisyonda kalın",
        "Diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "Her bacak 2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lomber Erector Spinae", "Glutes", "Piriformis"],
      warnings: ["Ani hareketlerden kaçının", "Ra gelmelidir"],
    },
    "dead-bug": {
      title: "Dead Bug",
      description: "Core stabilizasyon ve koordinasyon.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: ["Sırtüstü, kol bacak havada", "Karşı kol bacak uzat", "Bel yere basık", "Yavaş değiştir", "Nefes kontrolü"],
      sets: 3,
      reps: "10 her taraf",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Core", "Hip Flexors"],
      warnings: ["Bel kalkmasın"],
    },
    "plank": {
      title: "Plank",
      description: "İzometrik core güçlendirme.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Dirsek üzerinde", "Vücut düz hat", "Core sıkı", "30-60 saniye", "Nefes almaya devam"],
      sets: 3,
      reps: "30-60 sn",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Core", "Shoulders"],
      warnings: ["Kalça düşmesin"],
    },
    "side-plank": {
      title: "Side Plank",
      description: "Oblik ve lateral core.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Yan destek", "Vücut düz", "Kalça yukarıda", "20-40 saniye", "Her taraf"],
      sets: 3,
      reps: "20-40 sn her taraf",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Obliques", "Quadratus Lumborum"],
      warnings: ["Omuz stabil"],
    },
    "mcgill-curl-up": {
      title: "McGill Curl-Up",
      description: "Bel dostu karın egzersizi.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: ["Sırtüstü, bir diz bükük", "Eller bel altında", "Sadece omuz kaldır", "10 saniye hold", "Bel nötr"],
      sets: 3,
      reps: "8-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Rectus Abdominis"],
      warnings: ["Boyun çekme yok"],
    },
    "quadruped-rock": {
      title: "Quadruped Rock Back",
      description: "Bel mobilizasyonu.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Dört ayak pozisyonu", "Kalçayı geriye itin", "Topuklara oturun", "Germe hissi", "10-15 tekrar"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lomber Extensors"],
      warnings: ["Ağrısız hareket"],
    },
    "prone-press-up": {
      title: "Prone Press-Up (McKenzie)",
      description: "Bel ekstansiyon mobilizasyonu.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Yüzüstü yat", "Elleri omuz altına", "Göğsü kaldır", "Kalça yerde", "10 saniye hold"],
      sets: 3,
      reps: "8-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae"],
      warnings: ["Ağrı artarsa durdurun"],
    },
    "standing-extension": {
      title: "Standing Back Extension",
      description: "Ayakta bel germe.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Ayakta dur", "Eller belde", "Geriye doğru eğil", "5 saniye", "Yavaş dön"],
      sets: 3,
      reps: "8-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Erector Spinae"],
      warnings: ["Denge için destek"],
    },
    "cat-camel": {
      title: "Cat-Camel Mobilization",
      description: "Omurga mobilite egzersizi.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Dört ayak", "Sırt yukarı (kedi)", "Sırt aşağı (deve)", "Yavaş ritm", "10-15 tekrar"],
      sets: 2,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Spinal Erectors", "Abs"],
      warnings: ["Ağrısız hareket"],
    },
    "child-pose": {
      title: "Child's Pose",
      description: "Bel germe ve rahatlama.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Dizler üstünde", "Kalça topuklara", "Kollar öne uzat", "30-60 saniye", "Derin nefes"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lomber Muscles", "Lats"],
      warnings: ["Diz ağrısı varsa yastık"],
    },
    "pelvic-clock": {
      title: "Pelvic Clock",
      description: "Pelvik mobilite ve kontrol.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: ["Sırtüstü, dizler bükük", "Pelvis saat gibi hareket", "12-3-6-9 pozisyonları", "Yavaş ve kontrollü", "Her yön 5 tekrar"],
      sets: 2,
      reps: "5 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Core", "Hip Muscles"],
      warnings: ["Küçük hareketler"],
    },
    "reverse-crunch": {
      title: "Reverse Crunch",
      description: "Alt karın hedefleme.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/pelvic-tilt-exercise-demonstration-animation.jpg`,
      instructions: ["Sırtüstü yat", "Dizleri göğse çek", "Kalça hafif kalk", "Kontrollü in", "Bel yerde"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Lower Abs"],
      warnings: ["Momentum yok"],
    },
    "pallof-press": {
      title: "Pallof Press",
      description: "Anti-rotasyon core.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Yan dur, band/kablo", "Göğse çek", "Öne bas", "Rotasyona direnmemek", "Her taraf"],
      sets: 3,
      reps: "10 her taraf",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Bant/Kablo",
      targetMuscles: ["Obliques", "Core"],
      warnings: ["Vücut stabil"],
    },
    "single-leg-bridge": {
      title: "Single Leg Bridge",
      description: "Unilateral glute ve hamstring.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Sırtüstü, bir ayak yukarı", "Tek ayakla köprü", "3 saniye hold", "Her taraf", "Kalça seviyede"],
      sets: 3,
      reps: "10 her taraf",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glutes", "Hamstring"],
      warnings: ["Bel nötr"],
    },
    "fire-hydrant": {
      title: "Fire Hydrant",
      description: "Hip abduktor ve glute.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Dört ayak", "Dizini yana kaldır", "Kalça stabil", "2 saniye hold", "Her taraf"],
      sets: 3,
      reps: "12-15 her taraf",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Glute Medius", "Hip External Rotators"],
      warnings: ["Sırt düz"],
    },
    "thoracic-extension-foam": {
      title: "Thoracic Extension (Foam Roller)",
      description: "Üst sırt mobilizasyonu.",
      image: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      video: `${BASE}/lower-back-pain-exercises-physiotherapy.jpg`,
      instructions: ["Sırtüstü, roller torasik altında", "Eller baş arkasında", "Geriye uzan", "5-10 tekrar", "Farklı seviyeler"],
      sets: 2,
      reps: "5-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Foam Roller",
      targetMuscles: ["Thoracic Spine"],
      warnings: ["Boyun ve belde kullanma"],
    },
  },
  "el-bilek": {
    "bilek-fleksiyonu": {
      title: "Bilek Fleksiyonu Egzersizi",
      description: "El bileği kaslarını güçlendiren ve karpal tünel sendromu tedavisinde kullanılan egzersiz.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: [
        "Önkolunuzu bir yüzeye yerleştirin, eli dışarıda bırakın",
        "Avucunuz yukarı bakacak şekilde pozisyon alın",
        "Hafif bir ağırlık tutun (veya ağırlıksız başlayın)",
        "Bileğinizi yukarı doğru kaldırın",
        "Yavaşça başlangıç pozisyonuna dönün",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Hafif Ağırlık (0.5-1 kg)",
      targetMuscles: ["Fleksor Karpi Radialis", "Fleksor Karpi Ulnaris"],
      warnings: ["Çok ağır ağırlık kullanmayın", "Ağrı hissederseniz durdurun"],
    },
    "parmak-germe": {
      title: "Parmak Germe Egzersizi",
      description: "Parmak kaslarını uzatmak ve esnekliği artırmak için.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Elinizi düz bir şekilde uzatın",
        "Diğer elinizle parmağınızı yavaşça geri çekin",
        "15-20 saniye tutun",
        "Her parmakla tekrarlayın",
        "Diğer elle de aynı işlemi yapın",
      ],
      sets: 2,
      reps: "Her parmak 1-2",
      restTime: 20,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Parmak Ekstansörleri", "Ele ve bilek kasları"],
      warnings: ["Aşırı zorlamayın", "Yavaş ve kontrollü çekin"],
    },
    "bilek-rotasyonu": {
      title: "Bilek Rotasyonu",
      description: "Bilek mobilitesini artıran dairesel hareket egzersizi.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Kolunuzu önünüzde tutun",
        "Bileğinizi yavaşça saat yönünde çevirin",
        "10 tekrar yapın",
        "Sonra ters yönde 10 tekrar",
        "Diğer bileğinizle tekrarlayın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Bilek Fleksörleri", "Bilek Ekstansörleri"],
      warnings: ["Hareket yumuşak olmalı", "Ağrı varsa durdurun"],
    },
    "kavrama-gucendirme": {
      title: "Kavrama Güçlendirme",
      description: "El kası gücünü artıran sıkma egzersizi.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: [
        "Stres topu veya yumuşak top tutun",
        "Elinizle maksimum kuvvetle sıkın",
        "5 saniye tutun",
        "Gevşetin ve tekrarlayın",
        "Her iki elle de yapın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Stres Topu",
      targetMuscles: ["Fleksör Dijitorum", "Thenar Kaslar"],
      warnings: ["El krampı olursa dinlenin", "Aşırı sıkmayın"],
    },
    "bilek-ekstansiyon": {
      title: "Bilek Ekstansiyon",
      description: "Bilek ekstansör güçlendirme.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: ["Önkol masada, el dışarıda", "Avuç aşağı", "Eli yukarı kaldır", "Yavaş in", "10-15 tekrar"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Hafif Ağırlık",
      targetMuscles: ["Ekstensor Karpi"],
      warnings: ["Hafif ağırlık"],
    },
    "parmak-yayma": {
      title: "Parmak Yayma",
      description: "Intrinsik el kasları.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Parmakları yay", "5 saniye tut", "Gevşet", "Band ile direnç ekle", "15-20 tekrar"],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Parmak Bandı (Opsiyonel)",
      targetMuscles: ["Interosseous"],
      warnings: ["Yavaş hareket"],
    },
    "thumb-opposition": {
      title: "Başparmak Opp Egzersizi",
      description: "Başparmak mobilitesi.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Başparmağı diğer parmaklara değdir", "Her parmağa sırayla", "10 set", "Her iki el", "Yavaş ve kontrollü"],
      sets: 3,
      reps: "10",
      restTime: 20,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Thenar Muscles"],
      warnings: ["Ağrı yok"],
    },
    "putty-grip": {
      title: "Therapy Putty Egzersizi",
      description: "El gücü ve koordinasyon.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Putty'yi sık", "Parmak pinch yap", "Roll et", "Twist yap", "5-10 dakika"],
      sets: 1,
      reps: "5-10 dakika",
      restTime: 0,
      difficulty: "Orta",
      equipment: "Therapy Putty",
      targetMuscles: ["Tüm El Kasları"],
      warnings: ["Yorgunluk hisset dinlen"],
    },
    "radial-ulnar-deviation": {
      title: "Radial-Ulnar Deviation",
      description: "Bilek yan hareketleri.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: ["Önkol destekli", "El dışarıda", "Bilegi yana hareket", "Her iki yön", "10-15 tekrar"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Hafif Ağırlık",
      targetMuscles: ["Bilek Yan Kasları"],
      warnings: ["Kontrollü hareket"],
    },
    "prayer-stretch": {
      title: "Prayer Stretch",
      description: "Ön kol fleksör germe.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Avuçları birleştir", "Dirsekler dışarı", "Eller aşağı in", "20-30 saniye", "Germe hissi"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Fleksör Kasları"],
      warnings: ["Yumuşak germe"],
    },
    "reverse-prayer": {
      title: "Reverse Prayer Stretch",
      description: "Ekstansör germe.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Eller arkada birleşik", "Avuç dışarı", "Yukarı çık", "20-30 saniye", "Germe hissedilmeli"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Ekstansör Kasları"],
      warnings: ["Aşırı germe yok"],
    },
    "tendon-glide": {
      title: "Tendon Gliding",
      description: "Tendon mobilizasyonu.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["5 pozisyon: düz, hook, table top, fist, straight", "Her pozisyon 5 sn", "10 set", "Yavaş geçiş", "Her el"],
      sets: 3,
      reps: "10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Fleksör Tendonlar"],
      warnings: ["Ağrı varsa durdurun"],
    },
    "thumb-pinch": {
      title: "Thumb Pinch Strengthening",
      description: "Pinch grip güçlendirme.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Putty veya mandal", "Başparmak ile işaret parmağı sık", "5 saniye hold", "15 tekrar", "Her el"],
      sets: 3,
      reps: "15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Putty/Mandal",
      targetMuscles: ["Thenar", "Lateral Pinch"],
      warnings: ["Eklem ağrısı izle"],
    },
    "ball-squeeze": {
      title: "Ball Squeeze Variations",
      description: "Kavrama gücü varyasyonları.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Yumuşak top", "Full grip squeeze", "Pinch grip", "Fingertip grip", "Her grip 10 tekrar"],
      sets: 3,
      reps: "10 her grip",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Yumuşak Top",
      targetMuscles: ["Tüm Kavrama Kasları"],
      warnings: ["Yorgunluk hisset dur"],
    },
    "finger-ladder": {
      title: "Finger Ladder",
      description: "Parmak dexterity.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Duvarda parmak yürüme", "Yukarı çık", "Aşağı in", "Alternatif parmaklar", "10 tekrar"],
      sets: 3,
      reps: "10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Duvar",
      targetMuscles: ["Parmak Fleksör/Ekstansör"],
      warnings: ["Düşük başla"],
    },
    "coin-manipulation": {
      title: "Coin Manipulation",
      description: "Fine motor kontrol.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      instructions: ["Bozuk para parmaklar arası", "Parmaktan parmağa geçir", "5 dakika pratik", "Her el", "Koordinasyon geliştir"],
      sets: 1,
      reps: "5 dakika",
      restTime: 0,
      difficulty: "Orta",
      equipment: "Bozuk Para",
      targetMuscles: ["İntrinsik El Kasları"],
      warnings: ["Sabır gerekir"],
    },
    "wrist-curl-reverse": {
      title: "Reverse Wrist Curl",
      description: "Ekstansör izolasyon.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: ["Önkol destekli", "Avuç aşağı", "Dumbell tutun", "Bilekleri yukarı", "Yavaş kontrollü"],
      sets: 3,
      reps: "12-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Dumbbells",
      targetMuscles: ["Wrist Ekstansörler"],
      warnings: ["Hafif ağırlık"],
    },
    "pronation-supination": {
      title: "Pronation-Supination",
      description: "Önkol rotasyonu.",
      image: `${BASE}/hand-and-wrist-physiotherapy-exercises.jpg`,
      video: `${BASE}/wrist-flexion-exercise-demonstration.jpg`,
      instructions: ["Dirsek 90 derece", "Ağırlıklı sopa veya çekiç", "Avuç yukarı/aşağı rotate", "10-15 tekrar", "Her yön"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Ağırlıklı Sopa",
      targetMuscles: ["Pronator/Supinator"],
      warnings: ["Dirsek stabil"],
    },
  },
  ayak: {
    "ayak-bilegi-pumpa": {
      title: "Ayak Bileği Pompa Egzersizi",
      description:
        "Ayak bileği mobilitesini artıran ve şişliği azaltan temel egzersiz. Burkulma sonrası rehabilitasyonda kullanılır.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-pump-exercise-demonstration-animation.jpg`,
      instructions: [
        "Sırt üstü veya oturarak pozisyon alın",
        "Bacağınızı uzatın",
        "Ayak parmaklarınızı kendinize doğru çekin",
        "Sonra ayak parmaklarınızı öne doğru uzatın",
        "Hareketi ritmik bir şekilde tekrarlayın",
      ],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Tibialis Anterior", "Gastroknemius", "Soleus"],
      warnings: ["Hareket yumuşak olmalı", "Kramp hissederseniz dinlenin"],
    },
    "havlu-toplama": {
      title: "Havlu Toplama Egzersizi",
      description: "Ayak kemer kaslarını güçlendiren fonksiyonel egzersiz.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Bir havluyu yere yayın",
        "Ayaklarınızla havluyu toplamaya çalışın",
        "Parmaklarınızı kullanarak havluyu çekin",
        "Havlunun tamamını topladığınızda tekrar açın",
        "Her iki ayakla da yapın",
      ],
      sets: 3,
      reps: "5-10",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Havlu",
      targetMuscles: ["Ayak Kemer Kasları", "Fleksor Digitorum Brevis"],
      warnings: ["Kramp olursa dinlenin", "Yavaş başlayın"],
    },
    "ayak-bilegi-rotasyonu": {
      title: "Ayak Bileği Rotasyonu",
      description: "Ayak bileği mobilitesini artıran dairesel hareket.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Oturarak bir bacağınızı kaldırın",
        "Ayak bileğinizi saat yönünde çevirin",
        "10 tekrar yapın",
        "Ters yönde 10 tekrar",
        "Diğer ayakla tekrarlayın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Ayak Bileği Stabilizatörleri", "Peroneal Kaslar"],
      warnings: ["Hareket yumuşak olmalı", "Ağrı varsa durdurun"],
    },
    "topuk-yukseltme": {
      title: "Topuk Yükseltme (Calf Raise)",
      description: "Baldyr kaslarını güçlendiren egzersiz.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: [
        "Duvara veya sandalyeye destek olarak durun",
        "Parmak uçlarınıza kalkın",
        "Topuklarınızı maksimum yüksekliğe kaldırın",
        "2 saniye tutun",
        "Yavaşça inin ve tekrarlayın",
      ],
      sets: 3,
      reps: "12-15",
      restTime: 45,
      difficulty: "Orta",
      equipment: "Duvar/Sandalye",
      targetMuscles: ["Gastroknemius", "Soleus"],
      warnings: ["Denge için destek kullanın", "Ayak bileği ağrısı varsa durdurun"],
    },
    "single-leg-balance": {
      title: "Tek Ayak Denge",
      description: "Propriosepsiyon ve stabilite.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Tek ayak üzerinde dur", "30-60 saniye", "Gözler açık", "İlerleme: gözler kapalı", "Her ayak"],
      sets: 3,
      reps: "30-60 sn",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Ayak Bileği Stabilizatörleri"],
      warnings: ["Düşmemek için yakında destek olsun"],
    },
    "heel-walks": {
      title: "Topuk Yürüyüşü",
      description: "Anterior tibialis güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Topuklar üzerinde yürü", "Ayak parmakları yukarı", "20-30 adım", "Dik postür", "Dengeli"],
      sets: 3,
      reps: "20-30 adım",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Tibialis Anterior"],
      warnings: ["Kaygan zemin yok"],
    },
    "toe-walks": {
      title: "Parmak Ucu Yürüyüşü",
      description: "Gastrocnemius güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Ayak uçlarında yürü", "Topuklar havada", "20-30 adım", "Denge koru", "Yavaş başla"],
      sets: 3,
      reps: "20-30 adım",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Gastrocnemius", "Soleus"],
      warnings: ["Kramp olursa dinlen"],
    },
    "ankle-inversion": {
      title: "Ayak Bileği İnversiyon",
      description: "Inversör kas güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Band ayağa takılı", "Ayağı içe çevir", "Yavaş kontrollü", "10-15 tekrar", "Her ayak"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Tibialis Posterior", "İnversörler"],
      warnings: ["Aşırı inversiyon yok"],
    },
    "ankle-eversion": {
      title: "Ayak Bileği Eversiyon",
      description: "Eversör kas güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Band ayağa takılı", "Ayağı dışa çevir", "Kontrollü hareket", "10-15 tekrar", "Her ayak"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Peroneus Longus", "Peroneus Brevis"],
      warnings: ["Band gerginliğini ayarla"],
    },
    "arch-strengthening": {
      title: "Ayak Kemeri Güçlendirme",
      description: "İntrinsik ayak kasları.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Oturarak ayak yere", "Kemer yükselt (short foot)", "5 saniye tut", "Parmaklar düz", "15-20 tekrar"],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Ekipman Yok",
      targetMuscles: ["İntrinsik Ayak Kasları"],
      warnings: ["Parmaklar kıvrılmasın"],
    },
    "toe-curls": {
      title: "Ayak Parmağı Curl",
      description: "Fleksör digitorum kuvvetlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Oturarak havlu yere", "Parmaklarla havluyu topla", "10-15 toplama", "Her ayak", "Direnç arttır"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Havlu",
      targetMuscles: ["Fleksör Digitorum"],
      warnings: ["Kramp olursa germe yap"],
    },
    "marble-pickup": {
      title: "Bilye Toplama",
      description: "Fine motor kontrol.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Yerde bilyeler", "Ayak parmaklarıyla topla", "Kaba koy", "10-20 bilye", "Her ayak"],
      sets: 3,
      reps: "10-20 bilye",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Bilyeler",
      targetMuscles: ["İntrinsik Kaslar"],
      warnings: ["Sabırlı ol"],
    },
    "calf-stretch-wall": {
      title: "Duvar Baldır Germe",
      description: "Gastrocnemius germe.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Duvara yaslan", "Arka bacak düz", "Topuk yere", "Öne eğil", "20-30 saniye"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Duvar",
      targetMuscles: ["Gastrocnemius"],
      warnings: ["Yumuşak germe"],
    },
    "soleus-stretch": {
      title: "Soleus Germe",
      description: "Derin baldır germe.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Duvara yaslan", "Arka diz hafif bükük", "Topuk yere", "Öne eğil", "20-30 saniye"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Duvar",
      targetMuscles: ["Soleus"],
      warnings: ["Topuk kalkmasın"],
    },
    "bosu-balance": {
      title: "BOSU Denge Egzersizi",
      description: "İleri propriosepsiyon.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["BOSU üzerinde dur", "Tek veya iki ayak", "30-60 saniye", "Dengeli kal", "Gözler açık/kapalı"],
      sets: 3,
      reps: "30-60 sn",
      restTime: 60,
      difficulty: "İleri",
      equipment: "BOSU Ball",
      targetMuscles: ["Stabilizatörler"],
      warnings: ["Güvenli alan"],
    },
    "ankle-alphabet": {
      title: "Ayak Bileği Alfabe",
      description: "ROM ve kontrol.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Otur ayak havada", "Ayakla harf yaz", "A-Z tüm alfabe", "Büyük harfler", "Her ayak"],
      sets: 2,
      reps: "1 alfabe",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Tüm Ayak Bileği Kasları"],
      warnings: ["Ağrısız ROM"],
    },
    "band-dorsiflexion": {
      title: "Band ile Dorsifleksiyon",
      description: "Anterior kas güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Band ayağa takılı", "Ayağı yukarı çek", "Yavaş in", "10-15 tekrar", "Her ayak"],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Orta",
      equipment: "Direnç Bandı",
      targetMuscles: ["Tibialis Anterior"],
      warnings: ["Band gerginliği ayarla"],
    },
    "calf-raise-single": {
      title: "Tek Bacak Calf Raise",
      description: "İleri baldır güçlendirme.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Tek ayak üzerinde", "Topuğu kaldır", "En üstte 2 sn", "Yavaş in", "10-15 tekrar"],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "İleri",
      equipment: "Step/Basamak (Opsiyonel)",
      targetMuscles: ["Gastrocnemius", "Soleus"],
      warnings: ["Denge için destek kullan"],
    },
    "plantar-fascia-stretch": {
      title: "Plantar Fasya Germe",
      description: "Ayak tabanı germe.",
      image: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      video: `${BASE}/ankle-and-foot-physiotherapy-rehabilitation.jpg`,
      instructions: ["Otur bacak uzat", "Havlu ayak altında", "Kendine çek", "Parmakları geriye", "20-30 saniye"],
      sets: 3,
      reps: "2-3",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Havlu/Band",
      targetMuscles: ["Plantar Fasya"],
      warnings: ["Yumuşak germe"],
    },
  },
}
