export const exerciseDetails: Record<string, Record<string, any>> = {
  "boyun-sirt": {
    "boyun-germe": {
      title: "Boyun Germe Egzersizi",
      description:
        "Boyun kaslarını gevşetmek ve boyun ağrılarını azaltmak için yapılan temel germe egzersiz. Özellikle uzun süre bilgisayar başında çalışanlar için faydalıdır.",
      image: "/neck-stretching-exercise-physiotherapy.jpg",
      video: "/neck-stretching-exercise-demonstration-animation.jpg",
      instructions: [
        "Dik bir şekilde oturun veya ayakta durun",
        "Başınızı yavaşça sağa doğru eğin, kulağınızı omzunuza yaklaştırın",
        "15-30 saniye bu pozisyonda bekleyin",
        "Başınızı merkeze getirin ve sol tarafa tekrarlayın",
        "Hareket sırasında omuzlarınızı gevşek tutun",
      ],
      sets: 3,
      reps: "Her yöne 2",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Levator Scapulae", "Üst Trapezius", "Sternokleidomastoid"],
      warnings: ["Ani hareketlerden kaçının", "Ağrı hissederseniz durdurun", "Derin nefes almayı unutmayın"],
    },
    "kedi-deve": {
      title: "Kedi-Deve Hareketi",
      description: "Omurga esnekliğini artıran ve sırt kaslarını gevşeten yoga kökenli bir fizyoterapi egzersizi.",
      image: "/placeholder.svg?height=600&width=800",
      video: "/cat-cow-exercise-demonstration-animation.jpg",
      instructions: [
        "Dört ayak üzerinde pozisyon alın (el ve dizler yerde)",
        "Ellerinizi omuz hizasında, dizlerinizi kalça hizasında yerleştirin",
        "Nefes vererek sırtınızı yukarı doğru kambur yapın (Kedi)",
        "Nefes alarak göğsünüzü öne itip sırtınızı aşağı doğru çökertin (Deve)",
        "Hareketi yavaş ve kontrollü şekilde tekrarlayın",
      ],
      sets: 2,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Erector Spinae", "Abdominal Kaslar", "Torasik Omurga"],
      warnings: ["Boyun ve bel bölgesini aşırı zorlamayın", "Hareket akıcı olmalı"],
    },
  },
  diz: {
    "kuadriseps-gucendirme": {
      title: "Kuadriseps Güçlendirme",
      description: "Diz stabilitesini artıran ve kuadriseps kasını güçlendiren temel rehabilitasyon egzersizi.",
      image: "/knee-rehabilitation-exercises-physical-therapy.jpg",
      video: "/quadriceps-strengthening-exercise-demonstration.jpg",
      instructions: [
        "Sandalyeye dik bir şekilde oturun",
        "Bir bacağınızı yavaşça düz bir şekilde kaldırın",
        "Ayak bileğinizi kendinize doğru çekin (dorsifleksiyon)",
        "Bacağınızı 5-10 saniye yukarıda tutun",
        "Yavaşça yere indirin ve diğer bacakla tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Sandalye",
      targetMuscles: ["Kuadriseps (Rectus Femoris, Vastus Lateralis)", "Vastus Medialis"],
      warnings: ["Diz ağrısı hissedersinizse durdurun", "Hareket yavaş ve kontrollü olmalı"],
    },
  },
  omuz: {
    sarkaç: {
      title: "Sarkaç Egzersizi (Pendulum)",
      description:
        "Omuz ağrıları ve donuk omuz için yapılan pasif hareket egzersizi. Omuz eklemini gevşetir ve hareket açıklığını artırır.",
      image: "/pendulum-shoulder-exercise-physiotherapy.jpg",
      video: "/shoulder-pendulum-exercise-demonstration-animation.jpg",
      instructions: [
        "Bir masaya yaslanarak öne doğru eğilin",
        "Sağlıklı kolunuzla masaya destek olun",
        "Ağrılı kolunuzu sarkıtın ve gevşetin",
        "Kolunuzu küçük daireler çizerek sallamaya başlayın",
        "Önce saat yönünde, sonra ters yönde çevirin",
        "Kaslarınızı gevşek tutun, ağırlık sallanımı sağlasın",
      ],
      sets: 3,
      reps: "10 her yön",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Masa/Sandalye",
      targetMuscles: ["Rotator Cuff", "Deltoid", "Omuz Kapsülü"],
      warnings: ["Kas gücü kullanmayın, salınım pasif olmalı", "Ağrı artarsa durdurun"],
    },
  },
  bel: {
    "pelvik-tilt": {
      title: "Pelvik Tilt Egzersizi",
      description:
        "Bel ağrılarını azaltan ve core kaslarını aktive eden temel fizyoterapi hareketi. Lomber lordozis ve postür düzeltmede etkilidir.",
      image: "/lower-back-pain-exercises-physiotherapy.jpg",
      video: "/pelvic-tilt-exercise-demonstration-animation.jpg",
      instructions: [
        "Sırt üstü yatın, dizlerinizi bükerek ayaklarınızı yere koyun",
        "Kollarınızı yanlarınızda rahat bir pozisyonda tutun",
        "Alt karın kaslarınızı sıkarak bel bölgenizi yere bastırın",
        "5-10 saniye bu pozisyonda tutun",
        "Gevşetin ve tekrarlayın",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Egzersiz Matı",
      targetMuscles: ["Transversus Abdominis", "Multifidus", "Pelvik Taban Kasları"],
      warnings: ["Nefes tutmayın", "Hareket küçük ve kontrollü olmalı"],
    },
  },
  "el-bilek": {
    "bilek-fleksiyonu": {
      title: "Bilek Fleksiyonu Egzersizi",
      description: "El bileği kaslarını güçlendiren ve karpal tünel sendromu tedavisinde kullanılan egzersiz.",
      image: "/hand-and-wrist-physiotherapy-exercises.jpg",
      video: "/wrist-flexion-exercise-demonstration.jpg",
      instructions: [
        "Önkolunuzu bir yüzeye yerleştirin, eli dışarıda bırakın",
        "Avucunuz yukarı bakacak şekilde pozisyon alın",
        "Hafif bir ağırlık tutun (veya ağırlıksız başlayın)",
        "Bileğinizi yukarı doğru kaldırın",
        "Yavaşça başlangıç pozisyonuna dönün",
      ],
      sets: 3,
      reps: "10-15",
      restTime: 45,
      difficulty: "Başlangıç",
      equipment: "Hafif Ağırlık (0.5-1 kg)",
      targetMuscles: ["Fleksor Karpi Radialis", "Fleksor Karpi Ulnaris"],
      warnings: ["Çok ağır ağırlık kullanmayın", "Ağrı hissederseniz durdurun"],
    },
  },
  ayak: {
    "ayak-bileği-pumpa": {
      title: "Ayak Bileği Pompa Egzersizi",
      description:
        "Ayak bileği mobilitesini artıran ve şişliği azaltan temel egzersiz. Burkulma sonrası rehabilitasyonda kullanılır.",
      image: "/ankle-and-foot-physiotherapy-rehabilitation.jpg",
      video: "/ankle-pump-exercise-demonstration-animation.jpg",
      instructions: [
        "Sırt üstü veya oturarak pozisyon alın",
        "Bacağınızı uzatın",
        "Ayak parmaklarınızı kendinize doğru çekin",
        "Sonra ayak parmaklarınızı öne doğru uzatın",
        "Hareketi ritmik bir şekilde tekrarlayın",
      ],
      sets: 3,
      reps: "15-20",
      restTime: 30,
      difficulty: "Başlangıç",
      equipment: "Ekipman Yok",
      targetMuscles: ["Tibialis Anterior", "Gastroknemius", "Soleus"],
      warnings: ["Hareket yumuşak olmalı", "Kramp hissederseniz dinlenin"],
    },
  },
}
